added users orders route with jwt authentication
ElisaTumwebaze/auth-nodejs-API pull request #1
Opened 2021-05-19 13:37 UTC by ElisaTumwebaze

2021-05-19 14:01 UTC, katunold requested changes

2021-05-19 14:01 UTC, katunold commented on controllers/userController.js
> +    post_orders =verifyToken,(req,res)=>{
@ElisaTumwebaze  Kindly add the validation middleware at the route level, to have this organised in a much better way

2021-05-19 14:01 UTC, katunold commented on controllers/userController.js
> +module.exports ={signup_user,login_user,post_orders}
Kindly add an empty line character at the end of this file

2021-05-19 14:01 UTC, katunold commented on routes/authRoutes.js
>  module.exports = router;
Kindly add an empty line character at the end of this file

2021-05-20 14:05 UTC, Luleherll commented on controllers/userController.js
> +    post_orders =verifyToken,(req,res)=>{
@ElisaTumwebaze JWT middleware has to be at a route definition

2021-05-25 09:11 UTC, merged

2021-05-25 09:13 UTC, ElisaTumwebaze commented
separated login and signup controllers to make the code easily manageable